namespace GL.Servers.GS.Logic.Enums
{
    public enum ServiceNode
    {
        DEFAULT,
        SERVICE_NODE_TYPE_ACCOUNT_DIRECTORY,
        SERVICE_NODE_TYPE_ZONE_CONTAINER,
        SERVICE_NODE_TYPE_AVATAR_CONTAINER,
        SERVICE_NODE_TYPE_PARTY_CONTAINER,
        SERVICE_NODE_TYPE_GLOBAL_CHAT,
        SERVICE_NODE_TYPE_MATCHMAKING
    }
}