namespace GL.Servers.CoC.Logic.Enums
{
    public enum Gamefile
    {
        Null,
        Building,
        Locale,
        Resource,
        Character,
        Animation,
        Projectile,
        BuildingClass,
        Obstacle,
        Effect,
        ParticleEmitter,
        ExperienceLevel,
        Trap,
        AllianceBadge,
        Global,
        TownHall,
        Alliance_Portal,
        Npc,
        Deco,
        ResourcePack,
        Shield,
        Mission,
        BillingPackage,
        Achievement,
        Credit,
        Faq,
        Spell,
        Hint,
        Heroe,
        League,
        New,

        AllianceBadgeLayer = 34,
        Variable = 37,
        Gem_Bundle,
        Village_Object,
    }
}
