SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;


CREATE TABLE `Battles` (
  `HighID` int(10) UNSIGNED NOT NULL,
  `LowID` int(10) UNSIGNED NOT NULL,
  `Data` text NOT NULL DEFAULT '{}'
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `Clans` (
  `HighID` int(10) UNSIGNED NOT NULL,
  `LowID` int(10) UNSIGNED NOT NULL,
  `Data` text NOT NULL DEFAULT '{}'
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `Players` (
  `HighID` int(10) UNSIGNED NOT NULL,
  `LowID` int(10) UNSIGNED NOT NULL,
  `Data` text NOT NULL DEFAULT '{}'
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `Tournaments` (
  `HighID` int(10) UNSIGNED NOT NULL,
  `LowID` int(10) UNSIGNED NOT NULL,
  `Data` text NOT NULL DEFAULT '{}'
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


ALTER TABLE `Battles`
  ADD PRIMARY KEY (`HighID`,`LowID`),
  ADD KEY `INDEX` (`HighID`,`LowID`) USING BTREE;

ALTER TABLE `Clans`
  ADD PRIMARY KEY (`HighID`,`LowID`),
  ADD KEY `INDEX` (`HighID`,`LowID`) USING BTREE;

ALTER TABLE `Players`
  ADD PRIMARY KEY (`HighID`,`LowID`),
  ADD KEY `INDEX` (`HighID`,`LowID`) USING BTREE;

ALTER TABLE `Tournaments`
  ADD PRIMARY KEY (`HighID`,`LowID`),
  ADD KEY `INDEX` (`HighID`,`LowID`) USING BTREE;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
